// Generated by CoffeeScript 1.11.1
var Button;

Button = (function() {
  function Button(parent, x, y, w, h, key, txt) {
    var p;
    this.parent = parent;
    p = parent;
    this.x = p.x + p.w * x / 60;
    this.y = p.y + p.h * y / 60;
    this.w = p.w * w / 60;
    this.h = p.h * h / 60;
    this.key = key;
    this.txt = txt;
  }

  Button.prototype.draw = function() {
    fill(255);
    rect(this.x, this.y, this.w - 1, this.h - 1);
    fill(0);
    return text(this.txt, this.x + this.w / 2, this.y + this.h / 2);
  };

  Button.prototype.mousePressed = function() {
    if ((this.x <= mouseX && mouseX <= this.x + this.w) && mouseY >= this.y && mouseY <= this.y + this.h) {
      return this.parent.process(this.key);
    }
  };

  Button.prototype.keyPressed = function(key) {
    if (this.key === key) {
      return this.parent.process(this.key);
    }
  };

  return Button;

})();
