// Generated by CoffeeScript 1.11.1
var Player;

Player = (function() {
  function Player(keys, x, y, w, h) {
    this.keys = keys;
    this.x = width * x / 60;
    this.y = height * y / 60;
    this.w = width * w / 60;
    this.h = height * h / 60;
    this.history = [3];
    this.target = 2;
    this.count = 0;
    this.buttons = [];
    this.buttons.push(new Button(this, 5, 10, 20, 10, "", "3"));
    this.buttons.push(new Button(this, 35, 10, 20, 10, "", "2"));
    this.buttons.push(new Button(this, 20, 30, 20, 10, keys[0], "undo"));
    this.buttons.push(new Button(this, 0, 45, 20, 10, keys[1], "+2"));
    this.buttons.push(new Button(this, 20, 45, 20, 10, keys[2], "*2"));
    this.buttons.push(new Button(this, 40, 45, 20, 10, keys[3], "/2"));
  }

  Player.prototype.draw = function() {
    var button, i, len, ref, results;
    fill(255);
    rect(this.x, this.y, this.w - 1, this.h - 1);
    this.buttons[0].txt = this.top().toString();
    this.buttons[1].txt = this.target.toString();
    ref = this.buttons;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      button = ref[i];
      results.push(button.draw());
    }
    return results;
  };

  Player.prototype.mousePressed = function() {
    var button, i, len, ref, results;
    ref = this.buttons;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      button = ref[i];
      results.push(button.mousePressed());
    }
    return results;
  };

  Player.prototype.keyPressed = function(key) {
    var button, i, len, ref, results;
    ref = this.buttons;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      button = ref[i];
      results.push(button.keyPressed(key));
    }
    return results;
  };

  Player.prototype.process = function(key) {
    if (key === this.keys[0] && this.history.length > 1) {
      this.history.pop();
    }
    if (key === this.keys[1]) {
      this.save(this.top() + 2);
    }
    if (key === this.keys[2]) {
      this.save(this.top() * 2);
    }
    if (key === this.keys[3] && this.top() % 2 === 0) {
      return this.save(this.top() / 2);
    }
  };

  Player.prototype.save = function(value) {
    var d, ms;
    this.count++;
    this.history.push(value);
    if (this.target === this.top()) {
      d = new Date();
      ms = d.getTime();
      return this.stopp = ms;
    }
  };

  Player.prototype.score = function() {
    return (this.stopp - this.start) / 1000 + this.count * 10;
  };

  Player.prototype.top = function() {
    return this.history[this.history.length - 1];
  };

  Player.prototype.finished = function() {
    return this.top() === this.target;
  };

  Player.prototype.perfect = function(level) {
    return this.finished() && this.count <= level;
  };

  return Player;

})();
