// Generated by CoffeeScript 1.11.1
var Game, draw, game, keyPressed, mousePressed, setup,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

game = 0;

Game = (function() {
  function Game() {
    this.players = [];
    this.level = 1;
    this.players.push(new Player("WASD", 0, 0, 30, 60));
    this.players.push(new Player("&%('", 30, 0, 30, 60));
    this.createProblem();
  }

  Game.prototype.createProblem = function() {
    var a, b, d, i, len, lst, ms, player, ref, results, target;
    target = a = 1 + int(random(20));
    lst = [a];
    while (lst.length - 1 < this.level) {
      b = 0;
      switch (int(random(3))) {
        case 0:
          b = a - 2;
          break;
        case 1:
          b = a * 2;
          break;
        case 2:
          if (a % 2 === 0) {
            b = a / 2;
          }
      }
      if (b > 0 && indexOf.call(lst, b) < 0) {
        a = b;
        lst.push(b);
      }
    }
    d = new Date();
    ms = d.getTime();
    ref = this.players;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      player = ref[i];
      player.history = [lst[lst.length - 1]];
      player.target = target;
      player.count = 0;
      results.push(player.start = ms);
    }
    return results;
  };

  return Game;

})();

setup = function() {
  createCanvas(windowWidth, windowHeight);
  console.log("a");
  game = new Game();
  return textAlign(CENTER, CENTER);
};

draw = function() {
  var i, len, player, ref, results;
  ref = game.players;
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    player = ref[i];
    results.push(player.draw());
  }
  return results;
};

mousePressed = function() {
  var i, len, player, ref, results;
  ref = game.players;
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    player = ref[i];
    results.push(player.mousePressed());
  }
  return results;
};

keyPressed = function() {
  var finished, i, j, len, len1, perfect, player, ref, ref1, s;
  finished = 0;
  perfect = 0;
  ref = game.players;
  for (i = 0, len = ref.length; i < len; i++) {
    player = ref[i];
    if (player.finished()) {
      finished++;
    }
    if (player.perfect(game.level)) {
      perfect++;
    }
    player.keyPressed(key);
  }
  if (key === ' ' && finished > 0) {
    if (perfect > 0) {
      game.level++;
    } else {
      game.level--;
    }
    if (game.level === 0) {
      game.level = 1;
    }
    s = "";
    ref1 = game.players;
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      player = ref1[j];
      s = s + player.score() + "  ";
    }
    alert(s);
    return game.createProblem();
  }
};
