// Generated by CoffeeScript 1.11.1
var draw, keyPressed, mousePressed, players, setup;

players = [];

setup = function() {
  createCanvas(windowWidth, windowHeight);
  textAlign(CENTER, CENTER);
  textSize(30);
  players.push(new Player("WASD", 0, 0, 30, 60));
  return players.push(new Player("&%('", 30, 0, 30, 60));
};

draw = function() {
  var i, len, player, results;
  results = [];
  for (i = 0, len = players.length; i < len; i++) {
    player = players[i];
    results.push(player.draw());
  }
  return results;
};

mousePressed = function() {
  var i, len, player, results;
  results = [];
  for (i = 0, len = players.length; i < len; i++) {
    player = players[i];
    results.push(player.mousePressed());
  }
  return results;
};

keyPressed = function() {
  var i, len, player, results;
  results = [];
  for (i = 0, len = players.length; i < len; i++) {
    player = players[i];
    results.push(player.keyPressed(key));
  }
  return results;
};
